# Generated by Django 4.1.5 on 2023-01-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sent_to_api', models.BooleanField(default=False)),
                ('result_api', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name_plural': "Cashback's",
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=11)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.PositiveIntegerField()),
                ('cashback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cashback.cashback')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='cashback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_customer', to='cashback.customer'),
        ),
    ]
